server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  jwt:
    secret: test-v3ryLo0ngAndS3cretKeyForJwtTokenGenerationMustBeAtLeast256Bits

management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: "http://localhost:9411/api/v2/spans"

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/login, /reissue

        - id: user-service-register
          uri: lb://user-service
          predicates:
            - Path=/api/users
            - Method=POST

        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthorizationHeaderFilter

        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**
          filters:
            - AuthorizationHeaderFilter

        - id: driver-service-register
          uri: lb://driver-service
          predicates:
              - Path=/api/drivers
              - Method=POST

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
          filters:
            - AuthorizationHeaderFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - AuthorizationHeaderFilter

        - id: matching-service
          uri: lb://matching-service
          predicates:
            - Path=/api/matches/**
          filters:
            - AuthorizationHeaderFilter

        - id: geospatial-service
          uri: lb://geospatial-service
          predicates:
            - Path=/api/locations/**
          filters:
            - AuthorizationHeaderFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthorizationHeaderFilter

        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/prices/**
          filters:
            - AuthorizationHeaderFilter

        - id: trip-service-websocket
          uri: lb:ws://trip-service
          predicates:
            - Path=/ws/trips/tracking/**
          filters:
            - WebSocketJwtFilter

        - id: geospatial-service-websocket
          uri: lb:ws://geospatial-service
          predicates:
            - Path=/ws/location/**
          filters:
            - WebSocketJwtFilter